### ISSUE TITLE
Couldn't install Kryptonite

### ISSUE THREAD

**Issue by RinnieX** [mayankk2308/kryptonite#6]
### Problem Description
Hello,

I have a Radeon R9 Nano that shows "No Removable GPU" on my MacBook. I tried to install kryptonite through the terminal and this is what I get.

zsh: read-only file system: Installer.zip
ditto: Installer.zip: No such file or directory
cd: no such file or directory: Installer
chmod: installer.sh: No such file or directory
zsh: no such file or directory: ./installer.sh
zsh: no matches found: Installer*

I'm so confused! I followed the steps and things don't work for me. Could someone please explain to me what I did wrong? Also, I notice when trying to copy and paste the script to Terminal it says Make sure to select the boot disk you created in the previous step or use your existing bootloader disk." How do I select that? Please help. Thank you in advance. 

I have macOS Big Sur, version 11.4
MacBook Pro (13-inch,2017, Four Thunderbolt 3 Ports)
Processor 3.1 GHz Dual-Core Intel Core i5

**Comment by mayankk2308** [comment]
After opening a Terminal session, can you share output of:
```shell
pwd
```

Ideally it should be pointing to your home/user directory. In your case, it seems like you are running the command from a directory which is located on the macOS read-only volume.

I also updated the README with a slightly updated command. Please try that as well.

**Comment by RinnieX** [comment]
rinniexiao@Rinnies-Macbook-Pro ~ % cd
rinniexiao@Rinnies-Macbook-Pro ~ % pwd
/Users/rinniexiao
rinniexiao@Rinnies-Macbook-Pro ~ % curl -qLs https://github.com/mayankk2308/kryptonite/raw/main/Installer/Installer.zip > Installer.zip; ditto -x -k Installer.zip .; cd Installer; chmod +x installer.sh; ./installer.sh; cd ../; rm -rf Installer*

ditto: Couldn't read PKZip signature
cd: no such file or directory: Installer
chmod: installer.sh: No such file or directory
zsh: no such file or directory: ./installer.sh
zsh: no matches found: Installer*
rinniexiao@Rinnies-Macbook-Pro /Users % 

This is what I get after I typed in pwd and followed by the scripts.

**Comment by RinnieX** [comment]
updates:

rinniexiao@Rinnies-Macbook-Pro ~ % cd /Volumes/KRYPTONITE 
rinniexiao@Rinnies-Macbook-Pro KRYPTONITE % pwd
/Volumes/KRYPTONITE
rinniexiao@Rinnies-Macbook-Pro KRYPTONITE % curl -qLs https://github.com/mayankk2308/kryptonite/raw/main/Installer/Installer.zip > Installer.zip; ditto -x -k Installer.zip .; cd Installer; chmod +x installer.sh; ./installer.sh; cd ../; rm -rf Installer*

ditto: Couldn't read PKZip signature
cd: no such file or directory: Installer
chmod: installer.sh: No such file or directory
zsh: no such file or directory: ./installer.sh
zsh: no matches found: Installer*

I created a new MS-DOS(FAT32) partition (external) disk and that's the result I got in Terminal. Still wasn't sure where it went wrong. I tried to do it manually too but I got stuck after I downloaded the Kryptonite-DEBUG.zip and extracted it, dragged it to the external disk. After that, I wasn't sure how to update config.plist and so on....

I'm very new to this, so please be patient with me. I apologize in advance. Thank you.

**Comment by mayankk2308** [comment]
Why are you doing `cd /Volumes/KRYPTONITE/` first? It's not required and doesn't say so anywhere in the instructions.

**Comment by mayankk2308** [comment]
@RinnieX I've updated the README with an updated command. Can you please try that and let me know how it goes?

**Comment by RinnieX** [comment]
I don't see any differences.... the outcome is still the same.

According to manual installation, I dragged the EFI folder onto a MS-DOS volume and then restart the computer but the disk that I created didn't show up on the startup. Did I do it wrong? which EFI folder should I copy to the disk, the Kryptonite-Release or the OpenCore-0.7.1-RELEASE?

Another question is on step 4 of the installation, when using the OpenCore to create a new partition of the external disk, I copy the EFI folder from kyrptonite-release.zip to the disk.  Was this process simplified? Because I watched a few videos tutorial about OpenCore and how to create a bootable macOS and their steps are much more complex... 

if it is simplified, could you recommend me a good video tutorial please, thank you.

**Comment by mayankk2308** [comment]
@RinnieX other OpenCore tutorials do not apply - this is simplified.

Can you try running just this:
```shell
curl -qLs https://github.com/mayankk2308/kryptonite/raw/main/Installer/Installer.zip -o Installer.zip
```

This should give you an Installer zip file. Unzip that and see what files you get inside. If everything looks good, go to the directory in Terminal and run the installer:
```
cd Installer
chmod +x installer.sh
./installer.sh
```

**Comment by RinnieX** [comment]
<img width="579" alt="Screen Shot 2021-07-13 at 9 14 41 AM" src="https://user-images.githubusercontent.com/87279406/125374972-c4328700-e3ba-11eb-9a05-78eb357d392d.png">

i ran it and i don't see anything..

**Comment by mayankk2308** [comment]
@RinnieX open this folder and unzip the file in Finder.

**Comment by RinnieX** [comment]
<img width="568" alt="Screen Shot 2021-07-13 at 9 20 08 AM" src="https://user-images.githubusercontent.com/87279406/125375411-900b9600-e3bb-11eb-8a03-870abee9681b.png">


think i got something.. i downloaded the zip and run it through the terminal and used rest of the code you provided and this what i got so far. Couldn't find the OpenCore....

**Comment by mayankk2308** [comment]
Press N. Read everything the script says and the instructions in the README.

**Comment by RinnieX** [comment]
<img width="580" alt="Screen Shot 2021-07-13 at 9 39 13 AM" src="https://user-images.githubusercontent.com/87279406/125376714-3193e700-e3be-11eb-8341-612ffbf635be.png">

I tried it twice and it failed to download. 

I only saw nvidia eGPU, but I have AMD eGPU but from the README if I understand correctly I have to manually patch it into boot-args String in configplist in the NVRAM section later, right?

**Comment by mayankk2308** [comment]
@RinnieX I don't understand what is going on with your system because it is not able to download or save stuff. You've done everything right so far in the above screenshot. Do you have some VPN/Firewall stuff that's blocking things or something similar? Or do you have some custom developer tools (`zip`/`unzip`)? In the meantime, since you have a volume ready, you can try these manual instructions:

1. Rename your volume to `KRYPTONITE`.
1. Download Kryptonite-RELEASE from the Releases page.
1. Unzip and copy the EFI folder to your created disk. Then edit the config.plist file and add the required boot-args you need. You should only need `krygpu=AMD`.
1. Bless the bootloader as follows:
   ```shell
   sudo bless --folder /Volumes/KRYPTONITE/EFI/BOOT --label Kryptonite
   ```
1. When booting the system, press and hold OPTION key, then select the Kryptonite boot disk.

This will launch another boot menu where you can select your macOS boot drive. Booting from here will patch the system in memory.

**Comment by RinnieX** [comment]
<img width="565" alt="Screen Shot 2021-07-13 at 10 07 58 AM" src="https://user-images.githubusercontent.com/87279406/125379074-702ba080-e3c2-11eb-8cde-ae8b1be6438c.png">


I think I got it!!!! I closed an app that I have that might've caused the problem.  Since the download is completed, do I still need to edit the config.plist file to add krygpu=AMD?  or is it automatically applied?

**Comment by mayankk2308** [comment]
See README.

**Comment by RinnieX** [comment]
After it completed the download, when I restarted my computer and holding the OPT, I still didn't see my external disk on the boot picker.....

PS the app is called LULU

**Comment by mayankk2308** [comment]
@RinnieX Again, I don’t know the issue on your end and can’t do much on my end to resolve it. If your volume has been formatted by the script it should show up unless you actually have a 2018 MacBook Pro with T2 (in which case you would need to disable security and enable external driver boots).

**Comment by RinnieX** [comment]
<img width="1059" alt="Screen Shot 2021-07-13 at 10 37 12 AM" src="https://user-images.githubusercontent.com/87279406/125381582-bd117600-e3c6-11eb-96fb-59472acb6025.png">
<img width="584" alt="Screen Shot 2021-07-13 at 10 37 59 AM" src="https://user-images.githubusercontent.com/87279406/125381583-bf73d000-e3c6-11eb-944e-01877b145b12.png">
<img width="611" alt="Screen Shot 2021-07-13 at 10 40 03 AM" src="https://user-images.githubusercontent.com/87279406/125381585-c0a4fd00-e3c6-11eb-93e3-d4ba1f583921.png">
